

GRANT CREATE TABLE, CREATE SEQUENCE, CREATE PROCEDURE, CREATE TRIGGER, CREATE USER, DROP USER, CREATE TABLESPACE, DROP TABLESPACE, GRANT ANY ROLE TO ISSVOTE IDENTIFIED BY p123;
GRANT CONNECT, CREATE SESSION, RESOURCE TO ISSVOTE WITH ADMIN OPTION;

GRANT CONNECT, CREATE ROLE, DROP ANY ROLE, GRANT ANY ROLE 
TO ISSVOTE_SEC_MANAGER IDENTIFIED BY p123; 

GRANT CONNECT TO ISSVOTE_SEC_ADMIN IDENTIFIED BY p123;

CREATE ROLE ISS_ROLE;
GRANT CONNECT TO ISS_ROLE;